
![Inicio de sesion](https://github.com/andres-alvarez19/estacionamiento-ufro/blob/main/deliverables/Mockups/Inicio%20de%20sesion.png)
![Dashboard](https://github.com/andres-alvarez19/estacionamiento-ufro/blob/main/deliverables/Mockups/Dashboard.png)
![Parking map](https://github.com/andres-alvarez19/estacionamiento-ufro/blob/main/deliverables/Mockups/Parking%20map.png)
![Parking map-1](https://github.com/andres-alvarez19/estacionamiento-ufro/blob/main/deliverables/Mockups/Parking%20map-1.png)
![History](https://github.com/andres-alvarez19/estacionamiento-ufro/blob/main/deliverables/Mockups/History.png)
![Payment methods](https://github.com/andres-alvarez19/estacionamiento-ufro/blob/main/deliverables/Mockups/Payment%20methods.png)
![Profile](https://github.com/andres-alvarez19/estacionamiento-ufro/blob/main/deliverables/Mockups/Profile.png)
![Reservar](https://github.com/andres-alvarez19/estacionamiento-ufro/blob/main/deliverables/Mockups/Reservar.png)
![Settings](https://github.com/andres-alvarez19/estacionamiento-ufro/blob/main/deliverables/Mockups/Settings.png)
![Vehicle](https://github.com/andres-alvarez19/estacionamiento-ufro/blob/main/deliverables/Mockups/Vehicle.png)
